-- ============================================================================
-- V2: seed de produtos de atacado (fornecedor - tabela de precos 26/08)
-- ============================================================================
-- Importa o catalogo de carnes, hortifruti, frango, embutidos e peixes
-- recebido do fornecedor em tabela2608.pdf. O SKU usado eh o codigo do
-- fornecedor (coluna "Codigo" do PDF) para manter rastreabilidade.
-- ============================================================================

-- Grupo: BATATA /VEGETAIS
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('batata-newbraz-7-mm-5x-2-cx-10-kg-7481', '7481', 'Batata Newbraz 7 Mm ( 5x 2 ) CX 10 KG', 'hortifruti', 'kg', 13.30, 'BATATA NEWBRAZ 7 MM ( 5X 2 ) CX 10 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('batata-7mm-quality-fries-2-k-cx-12-kg-7344', '7344', 'Batata 7mm Quality Fries 2 K CX 12 KG', 'hortifruti', 'kg', 12.15, 'BATATA 7MM QUALITY FRIES 2 K CX 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('batata-new-braz-dupla-9-mm-8-x-1-50-12-kg-7578', '7578', 'Batata New Braz Dupla 9 Mm 8 X 1,50 12 KG', 'hortifruti', 'kg', 13.10, 'BATATA NEW BRAZ DUPLA 9 MM 8 X 1,50 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('batata-newbraz-10-mm-trad-8-x-1-5-cx-12-kg-7502', '7502', 'Batata Newbraz 10 Mm Trad. 8 X 1.5 CX 12 KG', 'hortifruti', 'kg', 10.75, 'BATATA NEWBRAZ 10 MM TRAD. 8 X 1.5 CX 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('batata-rapmix-10-mm-cx-6-x-2-kg-12-kg-7572', '7572', 'Batata Rapmix 10 Mm CX 6 X 2 KG = 12 KG', 'hortifruti', 'kg', 10.95, 'BATATA RAPMIX 10 MM CX 6 X 2 KG = 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('brocolis-cong-nutriz-cx-c-10-kg-5013', '5013', 'Brocolis Cong.-nutriz CX C/ 10 KG', 'hortifruti', 'kg', 10.69, 'BROCOLIS CONG.-NUTRIZ CX C/ 10 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('couve-flor-nao-cozido-nutriz-cx-4-x2-5-7191', '7191', 'Couve Flor Nao Cozido Nutriz CX 4 X2,5', 'hortifruti', 'kg', 12.49, 'COUVE FLOR NAO COZIDO NUTRIZ CX 4 X2,5', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('ervilha-fresca-nao-cozida-nutriz-4-x-2-5-7193', '7193', 'Ervilha Fresca Nao Cozida Nutriz 4 X 2,5', 'hortifruti', 'kg', 19.80, 'ERVILHA FRESCA NAO COZIDA NUTRIZ 4 X 2,5', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('espinafre-folhas-nao-cozido-nutriz-cx-4-x-2-50-10-kg-7378', '7378', 'Espinafre Folhas Nao Cozido Nutriz CX 4 X 2,50 (10 KG)', 'hortifruti', 'kg', 13.05, 'ESPINAFRE FOLHAS NAO COZIDO NUTRIZ CX 4 X 2,50 (10 KG)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('macaxeira-do-campo-10-kg-7258', '7258', 'Macaxeira Do Campo 10 KG', 'hortifruti', 'kg', 7.55, 'MACAXEIRA DO CAMPO 10 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('seleta-de-legumes-nao-cozida-nutriz-cx10-x-4-7402', '7402', 'Seleta De Legumes Nao Cozida Nutriz Cx10 X 4', 'hortifruti', 'kg', 12.25, 'SELETA DE LEGUMES NAO COZIDA NUTRIZ CX10 X 4', TRUE);

-- Grupo: CARNE DE CORDEIRO
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('pescoco-de-cordeiro-fat-cx-15-kg-7040', '7040', 'Pescoco De Cordeiro Fat. CX 15 KG', 'carnes-aves', 'kg', 26.90, 'PESCOCO DE CORDEIRO FAT. CX 15 KG', TRUE);

-- Grupo: CARNES BOVINAS
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('almondegas-institucional-qualit-beef-cx-03-kg-7596', '7596', 'Almondegas Institucional Qualit Beef CX 03 KG', 'carnes-aves', 'kg', 21.60, 'ALMONDEGAS INSTITUCIONAL QUALIT BEEF CX 03 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('bife-do-vazio-cong-beefqualyte-cx-20-kg-1203', '1203', 'Bife Do Vazio Cong. (beefqualyte) CX +- 20 KG', 'carnes-aves', 'kg', 37.70, 'BIFE DO VAZIO CONG. (BEEFQUALYTE) CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('capa-de-file-bov-cong-masterboi-cx-20-kg-7551', '7551', 'Capa De File BOV. Cong. Masterboi CX +- 20 KG', 'carnes-aves', 'kg', 34.30, 'CAPA DE FILE BOV. CONG. MASTERBOI CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('carne-moida-cong-de-bovino-tudbom-cx-15-kg-7546', '7546', 'Carne Moida Cong. De Bovino Tudbom CX 15 KG', 'carnes-aves', 'kg', 23.85, 'CARNE MOIDA CONG. DE BOVINO TUDBOM CX 15 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coracao-bov-fribev-cong-cx-20-kg-7604', '7604', 'Coracao BOV. Fribev Cong. CX +- 20 KG', 'carnes-aves', 'kg', 15.40, 'CORACAO BOV. FRIBEV CONG. CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('costela-bov-cong-em-tiras-cx-15-kg-beef-qualyte-7341', '7341', 'Costela BOV. Cong. Em Tiras CX +- 15 KG (beef Qualyte)', 'carnes-aves', 'kg', 23.90, 'COSTELA BOV. CONG. EM TIRAS CX +- 15 KG (BEEF QUALYTE)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('costela-bov-do-tras-rojao-cx-20-kg-beef-qualite-7340', '7340', 'Costela BOV. Do Tras. Rojao CX +- 20 KG (beef Qualite)', 'carnes-aves', 'kg', 22.90, 'COSTELA BOV. DO TRAS. ROJAO CX +- 20 KG (BEEF QUALITE)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('costela-de-ovino-palmeira-4528', '4528', 'Costela De Ovino (palmeira)', 'carnes-aves', 'kg', 36.60, 'COSTELA DE OVINO (PALMEIRA)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('costela-do-traseiro-bov-cong-minga-com-osso-friboi-7602', '7602', 'Costela Do Traseiro BOV Cong (minga Com Osso) Friboi', 'carnes-aves', 'kg', 26.25, 'COSTELA DO TRASEIRO BOV CONG (MINGA COM OSSO) FRIBOI', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxao-duro-cong-cx-20-kg-minerva-pul-7352', '7352', 'Coxao Duro Cong. CX +- 20 KG Minerva / PUL', 'carnes-aves', 'kg', 38.49, 'COXAO DURO CONG. CX +- 20 KG MINERVA / PUL', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxao-duro-cong-valencio-cx-20-kg-7433', '7433', 'Coxao Duro Cong. (valencio) CX +- 20 KG', 'carnes-aves', 'kg', 37.35, 'COXAO DURO CONG. (VALENCIO) CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxao-mole-cong-valencio-cx-20-kg-7399', '7399', 'Coxao Mole Cong. (valencio) CX +- 20 KG', 'carnes-aves', 'kg', 39.90, 'COXAO MOLE CONG. (VALENCIO) CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('cupim-bov-cong-grill-a-valencio-cx-20-kg-7618', '7618', 'Cupim BOV. Cong Grill (a) Valencio CX +- 20 KG', 'carnes-aves', 'kg', 45.20, 'CUPIM BOV. CONG GRILL (A) VALENCIO CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('cupim-bov-cong-b-master-boi-cx-20-kg-1190', '1190', 'Cupim BOV. Cong (b) Master Boi CX +- 20 KG', 'carnes-aves', 'kg', 36.49, 'CUPIM BOV. CONG (B) MASTER BOI CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('cupim-bovino-tipo-1998-valencio-cx-15-kg-7320', '7320', 'Cupim Bovino Tipo (1998) Valencio CX +- 15 KG', 'carnes-aves', 'kg', 42.90, 'CUPIM BOVINO TIPO (1998) VALENCIO CX +- 15 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('figado-bov-pul-minerva-cx-23-kg-7549', '7549', 'Figado BOV. PUL Minerva CX +- 23 KG', 'carnes-aves', 'kg', 15.39, 'FIGADO BOV. PUL MINERVA CX +- 23 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('file-bovino-s-c-4-5-cong-cx-20-kg-valencio-7613', '7613', 'File Bovino S/c 4/5 Cong. CX +- 20 KG Valencio', 'carnes-aves', 'kg', 94.90, 'FILE BOVINO S/C 4/5 CONG. CX +- 20 KG VALENCIO', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('filet-bov-congelado-gold-beef-cx-15-kg-7446', '7446', 'Filet BOV. Congelado Gold Beef CX +- 15 KG', 'carnes-aves', 'kg', 84.90, 'FILET BOV. CONGELADO GOLD BEEF CX +- 15 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('filezinho-da-picanha-sao-francisco-cx-20-kg-7587', '7587', 'Filezinho Da Picanha Sao Francisco CX +- 20 KG', 'carnes-aves', 'kg', 34.90, 'FILEZINHO DA PICANHA SAO FRANCISCO CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('fraldinha-bov-cong-diafragma-frigoraca-cx-25-kg-7616', '7616', 'Fraldinha BOV. Cong. Diafragma Frigoraca CX +- 25 KG', 'carnes-aves', 'kg', 32.90, 'FRALDINHA BOV. CONG. DIAFRAGMA FRIGORACA CX +- 25 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('maminha-bov-cong-minerva-pul-12-kg-1004', '1004', 'Maminha BOV. Cong. Minerva (PUL) +- 12 KG', 'carnes-aves', 'kg', 46.95, 'MAMINHA BOV. CONG. MINERVA (PUL) +- 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('maminha-bov-nac-plena-toda-hora-f-15-kg-1201', '1201', 'Maminha BOV Nac. (plena / Toda Hora) F +- 15 KG', 'carnes-aves', 'kg', 46.65, 'MAMINHA BOV NAC. (PLENA / TODA HORA) F +- 15 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('maminha-bov-cong-maturatta-cx-15-kg-friboi-7215', '7215', 'Maminha BOV. Cong Maturatta CX +- 15 KG (friboi)', 'carnes-aves', 'kg', 61.25, 'MAMINHA BOV. CONG MATURATTA CX +- 15 KG (FRIBOI)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('maminha-bov-congelada-1998-valencio-cx-20-kg-7480', '7480', 'Maminha BOV. Congelada 1998 Valencio CX +- 20 KG', 'carnes-aves', 'kg', 49.90, 'MAMINHA BOV. CONGELADA 1998 VALENCIO CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('picanha-bov-pul-argentina-cx-18-kg-7611', '7611', 'Picanha BOV. PUL Argentina CX +- 18 KG', 'carnes-aves', 'kg', 86.90, 'PICANHA BOV. PUL ARGENTINA CX +- 18 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('picanha-bov-uruguaia-pul-tapa-de-cuadril-a-cx-20-kg-7606', '7606', 'Picanha BOV. Uruguaia PUL (tapa De Cuadril) A CX +- 20 KG', 'carnes-aves', 'kg', 88.30, 'PICANHA BOV. URUGUAIA PUL (TAPA DE CUADRIL) A CX +- 20 KG', TRUE);

-- Grupo: CARNES DE SUINO
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('carne-temp-cong-suino-s-osso-lombo-contra-file-05-kg-7576', '7576', 'Carne Temp. Cong. Suino S/ Osso Lombo Contra File 05 KG', 'carnes-aves', 'kg', 23.30, 'CARNE TEMP. CONG. SUINO S/ OSSO LOMBO CONTRA FILE 05 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('costela-suina-cong-aurora-cx-c-10-kg-especial-4016', '4016', 'Costela Suina Cong. Aurora CX C/ +- 10 KG (especial)', 'carnes-aves', 'kg', 28.30, 'COSTELA SUINA CONG. AURORA CX C/ +- 10 KG (ESPECIAL)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('costela-suina-cong-adeel-baby-back-ribs-cx-15-kg-7600', '7600', 'Costela Suina Cong. ADEEL Baby Back Ribs CX +- 15 KG', 'carnes-aves', 'kg', 20.90, 'COSTELA SUINA CONG. ADEEL BABY BACK RIBS CX +- 15 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('lombo-suino-gold-meat-cong-cx-20-kg-7603', '7603', 'Lombo Suino Gold Meat Cong CX +- 20 KG', 'carnes-aves', 'kg', 20.75, 'LOMBO SUINO GOLD MEAT CONG CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('lombo-suino-nat-cong-adeel-cx-20-kg-7615', '7615', 'Lombo Suino Nat. Cong. ADEEL CX +- 20 KG', 'carnes-aves', 'kg', 20.25, 'LOMBO SUINO NAT. CONG. ADEEL CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('pernil-suino-s-osso-in-natura-adeel-cx-20-kg-7609', '7609', 'Pernil Suino S/ Osso In Natura (ADEEL) CX +- 20 KG', 'carnes-aves', 'kg', 17.35, 'PERNIL SUINO S/ OSSO IN NATURA (ADEEL) CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('pernil-suino-s-pele-s-osso-my-pork-cx-20-kg-7568', '7568', 'Pernil Suino S/ Pele S/ Osso My Pork CX +- 20 KG', 'carnes-aves', 'kg', 15.90, 'PERNIL SUINO S/ PELE S/ OSSO MY PORK CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('picanha-suina-temp-c-premiata-cx-15-kg-suinco-7127', '7127', 'Picanha Suina Temp. C. Premiata CX 15 KG (suinco)', 'carnes-aves', 'kg', 33.80, 'PICANHA SUINA TEMP. C. PREMIATA CX 15 KG (SUINCO)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('picanha-suina-temp-s-osso-pamplona-cx-10-kg-7384', '7384', 'Picanha Suina Temp. S/ Osso (pamplona) CX 10 KG', 'carnes-aves', 'kg', 29.55, 'PICANHA SUINA TEMP. S/ OSSO (PAMPLONA) CX 10 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('sobrepaleta-suina-fat-iqf-pt-800-gr-sd-7610', '7610', 'Sobrepaleta Suina Fat IQF Pt 800 Gr SD', 'carnes-aves', 'kg', 20.74, 'SOBREPALETA SUINA FAT IQF PT 800 GR SD', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('sobrepaleta-suina-cong-iwp-cx-12-kg-sadia-7150', '7150', 'Sobrepaleta Suina Cong. Iwp CX +- 12 KG Sadia', 'carnes-aves', 'kg', 18.30, 'SOBREPALETA SUINA CONG. IWP CX +- 12 KG SADIA', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('sobrepaleta-suina-pamplona-cx-10-kg-7271', '7271', 'Sobrepaleta Suina Pamplona CX 10 KG', 'carnes-aves', 'cx', 20.90, 'SOBREPALETA SUINA PAMPLONA CX 10 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('sobrepaleta-suina-s-osso-in-nat-cong-adeel-cx-20-kg-7608', '7608', 'Sobrepaleta Suina S/ Osso In Nat. Cong. (ADEEL) CX +- 20 KG', 'carnes-aves', 'kg', 18.49, 'SOBREPALETA SUINA S/ OSSO IN NAT. CONG. (ADEEL) CX +- 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('sobrepaleta-temp-suina-pamplona-cx-10-kg-7491', '7491', 'Sobrepaleta Temp. Suina Pamplona CX 10 KG', 'carnes-aves', 'kg', 22.30, 'SOBREPALETA TEMP. SUINA PAMPLONA CX 10 KG', TRUE);

-- Grupo: FRANGO E CORTES DE FRANGO
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('ave-natalina-temp-jaguar-cx-20-kg-7590', '7590', 'Ave Natalina Temp. Jaguar CX 20 KG', 'carnes-aves', 'kg', 12.99, 'AVE NATALINA TEMP. JAGUAR CX 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('carcaca-fgo-seara-1-20-cx-12-kg-2011', '2011', 'Carcaca FGO. Seara 1,20 CX 12 KG', 'carnes-aves', 'kg', 13.25, 'CARCACA FGO. SEARA 1,20 CX 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('carcaca-fgo-seara-1-10-cx-11-kg-2008', '2008', 'Carcaca FGO. Seara 1,10 CX 11 KG', 'carnes-aves', 'kg', 13.25, 'CARCACA FGO. SEARA 1,10 CX 11 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('carcaca-fgo-sadia-1-2-cx-12-kg-2005', '2005', 'Carcaca FGO. Sadia 1.2 CX 12 KG', 'carnes-aves', 'kg', 13.25, 'CARCACA FGO. SADIA 1.2 CX 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('codorna-cong-s-miudos-vg-12x0-820-kg-vila-germania-7520', '7520', 'Codorna Cong. S/ Miudos VG 12x0,820 KG (vila Germania)', 'carnes-aves', 'un', 48.40, 'CODORNA CONG. S/ MIUDOS VG 12X0,820 KG (VILA GERMANIA)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coracao-de-fgo-mfc-friato-cx-24x-0-800-cx-19-20-kg-7420', '7420', 'Coracao De FGO. (MFC) Friato CX 24x 0.800 = CX 19,20 KG', 'carnes-aves', 'kg', 35.70, 'CORACAO DE FGO. (MFC) FRIATO CX 24X 0.800 = CX 19,20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxa-s-coxa-sem-osso-c-pele-somaves-cx-20-kg-file-7614', '7614', 'Coxa S/ Coxa Sem Osso C/ Pele Somaves CX 20 KG (file)', 'carnes-aves', 'kg', 15.90, 'COXA S/ COXA SEM OSSO C/ PELE SOMAVES CX 20 KG (FILE)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxa-s-coxa-desossada-friato-cx-19-50-kg-file-7365', '7365', 'Coxa S/ Coxa Desossada Friato CX 19,50 KG (file)', 'carnes-aves', 'kg', 12.65, 'COXA S/ COXA DESOSSADA FRIATO CX 19,50 KG (FILE)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxa-s-coxa-cong-ind-cx-18-kg-guibom-7264', '7264', 'Coxa S/ Coxa Cong. Ind. CX 18 KG Guibom', 'carnes-aves', 'kg', 9.30, 'COXA S/ COXA CONG. IND. CX 18 KG GUIBOM', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxa-s-coxa-ind-somave-cx-18-kg-7305', '7305', 'Coxa S/ Coxa Ind. Somave CX 18 KG', 'carnes-aves', 'kg', 9.10, 'COXA S/ COXA IND. SOMAVE CX 18 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxa-sobrecoxa-cong-friato-envelopada-20-kg-7067', '7067', 'Coxa/sobrecoxa Cong. Friato Envelopada 20 KG', 'carnes-aves', 'kg', 9.10, 'COXA/SOBRECOXA CONG. FRIATO ENVELOPADA 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxinha-da-asa-fgo-cong-friato-cx-20-kg-7495', '7495', 'Coxinha Da Asa FGO. Cong. Friato CX 20 KG', 'carnes-aves', 'kg', 10.95, 'COXINHA DA ASA FGO. CONG. FRIATO CX 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coxinha-da-asa-indiv-guibom-cx-18-kg-7534', '7534', 'Coxinha Da Asa Indiv. Guibom CX 18 KG', 'carnes-aves', 'kg', 10.95, 'COXINHA DA ASA INDIV. GUIBOM CX 18 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('file-de-coxa-sobrecoxa-iqf-zip-cx-10-kg-aurora-7300', '7300', 'File De Coxa/sobrecoxa Iqf-zip CX 10 KG (aurora)', 'carnes-aves', 'kg', 17.25, 'FILE DE COXA/SOBRECOXA IQF-ZIP CX 10 KG (AURORA)', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('file-de-peito-fgo-guibon-cx-18-kg-2020', '2020', 'File De Peito FGO Guibon CX 18 KG', 'carnes-aves', 'kg', 15.45, 'FILE DE PEITO FGO GUIBON CX 18 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('file-de-peito-fgo-cx-20-kg-jagua-7008', '7008', 'File De Peito FGO CX 20 KG Jagua', 'carnes-aves', 'kg', 18.70, 'FILE DE PEITO FGO CX 20 KG JAGUA', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('file-de-peito-fgo-envelop-friato-cx-20-kg-7563', '7563', 'File De Peito FGO. Envelop. Friato CX 20 KG', 'carnes-aves', 'kg', 15.65, 'FILE DE PEITO FGO. ENVELOP. FRIATO CX 20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('file-de-peito-sassami-guibon-cx-18-kg-7442', '7442', 'File De Peito Sassami Guibon CX 18 KG', 'carnes-aves', 'kg', 15.50, 'FILE DE PEITO SASSAMI GUIBON CX 18 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('moela-de-frango-friato-24x-0-80-19-20-kg-7492', '7492', 'Moela De Frango Friato 24x 0,80 = 19,20 KG', 'carnes-aves', 'kg', 11.30, 'MOELA DE FRANGO FRIATO 24X 0,80 = 19,20 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('peito-de-fgo-cong-envelopado-cx-20-kg-friato-7379', '7379', 'Peito De FGO. Cong. Envelopado CX 20 KG Friato', 'carnes-aves', 'kg', 10.75, 'PEITO DE FGO. CONG. ENVELOPADO CX 20 KG FRIATO', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('peito-fgo-c-osso-copacol-cx-17-kg-7550', '7550', 'Peito FGO. C/ Osso Copacol CX 17 KG', 'carnes-aves', 'kg', 11.65, 'PEITO FGO. C/ OSSO COPACOL CX 17 KG', TRUE);

-- Grupo: LINGUICAS E EMBUTIDOS
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('bacon-em-manta-perdigao-7069', '7069', 'Bacon Em Manta Perdigao', 'laticinios-frios', 'kg', 27.60, 'BACON EM MANTA PERDIGAO', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('bacon-manta-pamplona-cx-10-kg-7415', '7415', 'Bacon Manta Pamplona CX 10 KG', 'laticinios-frios', 'kg', 28.90, 'BACON MANTA PAMPLONA CX 10 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-de-carne-suina-aurora-churrasco-5-x-5-25-kg-3006', '3006', 'Linguica De Carne Suina Aurora Churrasco 5 X 5 = 25 KG', 'laticinios-frios', 'kg', 16.80, 'LINGUICA DE CARNE SUINA AURORA CHURRASCO 5 X 5 = 25 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-de-fgo-aurora-cx-c-25-kg-3007', '3007', 'Linguica De FGO. Aurora CX C/ 25 KG', 'laticinios-frios', 'kg', 17.80, 'LINGUICA DE FGO. AURORA CX C/ 25 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-suina-nobre-2-x-5-kg-10-kg-3003', '3003', 'Linguica Suina Nobre 2 X 5 KG = 10 KG', 'laticinios-frios', 'kg', 14.90, 'LINGUICA SUINA NOBRE 2 X 5 KG = 10 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-de-pernil-c-pimenta-cong-1-kg-cx-12-kg-3016', '3016', 'Linguica De Pernil C/ Pimenta Cong. 1 KG CX 12 KG', 'laticinios-frios', 'kg', 19.80, 'LINGUICA DE PERNIL C/ PIMENTA CONG. 1 KG CX 12 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-mista-nobre-cx-c-25-kg-7064', '7064', 'Linguica Mista Nobre CX C/ 25 KG', 'laticinios-frios', 'pct', 14.30, 'LINGUICA MISTA NOBRE CX C/ 25 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-tipo-calabresa-adeel-cx-17-50-kg-7612', '7612', 'Linguica Tipo Calabresa ADEEL CX 17,50 KG', 'laticinios-frios', 'kg', 17.75, 'LINGUICA TIPO CALABRESA ADEEL CX 17,50 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-tipo-calabresa-def-fatiada-cx-08-kg-7421', '7421', 'Linguica Tipo Calabresa Def. Fatiada CX 08 KG', 'laticinios-frios', 'kg', 25.90, 'LINGUICA TIPO CALABRESA DEF. FATIADA CX 08 KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('linguica-tipo-calabresa-def-pamplona-4x-2-50-10-kg-7389', '7389', 'Linguica Tipo Calabresa Def. Pamplona 4x 2,50 = 10 KG', 'laticinios-frios', 'kg', 19.60, 'LINGUICA TIPO CALABRESA DEF. PAMPLONA 4X 2,50 = 10 KG', TRUE);

-- Grupo: MIUDOS
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('coracao-de-frango-imp-argentino-cedal-cx-15x-1kg-7366', '7366', 'Coracao De Frango Imp. Argentino Cedal CX 15x 1kg', 'carnes-aves', 'kg', 37.25, 'CORACAO DE FRANGO IMP. ARGENTINO CEDAL CX 15X 1KG', TRUE);
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('figado-bovino-cong-cx-25-kg-valencio-7504', '7504', 'Figado Bovino Cong. CX +- 25 KG (valencio)', 'carnes-aves', 'kg', 14.29, 'FIGADO BOVINO CONG. CX +- 25 KG (VALENCIO)', TRUE);

-- Grupo: PEIXES
INSERT INTO products (slug, sku, name, category, unit, price, description, available) VALUES ('file-de-panga-iqf-sup-premium-cx-10-kg-7499', '7499', 'File De Panga IQF Sup Premium CX 10 KG', 'congelados', 'kg', 25.60, 'FILE DE PANGA IQF SUP PREMIUM CX 10 KG', TRUE);
